CREATE DATABASE IF NOT EXISTS spider;
USE spider;
DROP TABLE IF EXISTS `blog`;
DROP TABLE IF EXISTS `collections`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `subscribe`;
DROP TABLE IF EXISTS `urlinfo`;
DROP TABLE IF EXISTS `user`;
